name: Testing
on:
  push:
    branches: main
    paths-ignore:
      - '.github/workflows/clang-formatter.yml'
      - 'project/discord-rpc/.clang-format'
      - 'LICENSE'
      - 'README.md'
      - 'haxelib.json'
      - 'hxformat.json'
  workflow_dispatch:
jobs:
  Job:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Install Libs
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt install libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev

      - name: Install Dependencies
        run: |
          haxelib install hxcpp --quiet
          haxelib dev hxdiscord_rpc .

      - name: Build Unix
        if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu')
        run: cd sample && haxe build-unix.hxml

      - name: Build Windows
        if: startsWith(matrix.os, 'windows')
        run: cd sample && haxe build-win.hxml
